"""HTML export service — renders dashboard to a standalone HTML document."""

from typing import Optional
from sqlalchemy.orm import Session
from app import models
from jinja2 import Template


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ dashboard.name }}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'IBM Plex Sans Arabic', Arial, sans-serif; background: #0f0e1c; color: #f4f4f8; padding: 24px; }
  h1 { font-size: 2rem; margin-bottom: 16px; color: #27CED7; }
  .page { margin-bottom: 40px; }
  .page-title { font-size: 1.4rem; color: #4137A8; border-bottom: 2px solid #4137A8; padding-bottom: 8px; margin-bottom: 16px; }
  .grid { display: grid; grid-template-columns: repeat(12, 1fr); gap: 12px; }
  .section-card { background: rgba(65,55,168,0.15); border: 1px solid rgba(65,55,168,0.3); border-radius: 12px; padding: 16px; }
  .section-title { font-size: 0.85rem; color: #9b9bb4; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px; }
  .section-type { font-size: 0.7rem; color: #4137A8; }
  .week-label { font-size: 0.75rem; color: #9b9bb4; margin-bottom: 24px; }
  footer { margin-top: 40px; font-size: 0.75rem; color: #6b6b8a; text-align: center; }
</style>
</head>
<body>
<h1>{{ dashboard.name }}</h1>
{% if week %}<div class="week-label">Week of {{ week }}</div>{% endif %}
{% for page in pages %}
<div class="page">
  <div class="page-title">{{ page.name }}</div>
  <div class="grid">
    {% for sec in page.sections %}
    <div class="section-card" style="grid-column: span {{ [sec.grid_item_json.get('w', 3), 12]|min }};">
      <div class="section-title">{{ sec.title }}</div>
      <div class="section-type">{{ sec.indicator_type }}</div>
    </div>
    {% endfor %}
  </div>
</div>
{% endfor %}
<footer>Generated by Team Dashboard Hub &bull; {{ now }}</footer>
</body>
</html>"""


def export_dashboard_html(dashboard: models.Dashboard, db: Session, week: Optional[str] = None) -> str:
    from datetime import datetime
    pages = db.query(models.Page).filter_by(dashboard_id=dashboard.id).order_by(models.Page.order).all()
    page_data = []
    for page in pages:
        sections = db.query(models.Section).filter_by(page_id=page.id).order_by(models.Section.order).all()
        page_data.append({
            "name": page.name,
            "sections": sections,
        })

    tmpl = Template(HTML_TEMPLATE)
    return tmpl.render(
        dashboard=dashboard,
        pages=page_data,
        week=week,
        now=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )
